/*
 * arduino.inc
 *
 *  Created: 14/04/2018 15:01:01
 *   Author: david
 */ 

 ;questo file permette di utilizzare i pin di arduino senza creare ambiguità con i pin ATmega

 .def PIN1 = PD0
 .def PIN2 = PD1
 .def PIN3 = PD3
 .def PIN4 = PD4
 .def PIN5 = PD5
 .def PIN6 = PD6
 .def PIN7 = PD7

 .def PIN8 = PB0
 .def PIN9 = PB1
 .def PIN10 = PB2
 .def PIN11 = PB3
 .def PIN12 = PB4
 .def PIN13 = PB5

 .def A0 = PC0
 .def A1 = PC1
 .def A2 = PC2
 .def A3 = PC3
 .def A4 = PC4
 .def A5 = PC5
