/*
 * arduino.inc
 *
 *  Created: 14/04/2018 15:01:01
 *   Author: david
 */ 

 ;questo file permette di utilizzare i pin di arduino senza creare ambiguità con i pin ATmega

 .equ PIN1 = PD0
 .equ PIN2 = PD1
 .equ PIN3 = PD3
 .equ PIN4 = PD4
 .equ PIN5 = PD5
 .equ PIN6 = PD6
 .equ PIN7 = PD7

 .equ PIN8 = PB0
 .equ PIN9 = PB1
 .equ PIN10 = PB2
 .equ PIN11 = PB3
 .equ PIN12 = PB4
 .equ PIN13 = PB5

 .equ A0 = PC0
 .equ A1 = PC1
 .equ A2 = PC2
 .equ A3 = PC3
 .equ A4 = PC4
 .equ A5 = PC5
